# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the application code into the container
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
# (Only if your application exposes a port)
EXPOSE 80

# Command to start your application (modify this based on your application)
CMD ["python", "TemperatureControlUnit.py"]
